#!/usr/bin/env python3
"""Generate ONE Playwright script that runs the whole core flow to Pending.

Why: running the 7 phase scripts as 7 separate browser_run_code_unsafe calls
costs a round trip plus model latency between every phase — that dominated the
17-minute run on 2026-07-30, not the browser work itself. Chaining them inside a
single call removes that overhead and returns per-phase timings so slow phases
are visible instead of guessed at.

DRY: the phase sources are read from the real skill scripts, never copied. Edit
those; re-run this to rebuild.

Usage:
  python3 build-composite-to-pending.py <medicare_id> [dev|prod] [out.js] \
      [--only 3,4,5,6,7] [--case-id CA-XXXXXXXX]

--only / --case-id are the RESUME path: when a run dies after the case already
exists, rebuild with just the remaining phases and seed the known case id so
phase 5 (PSS) can find it. Never re-run phase 1 on a resume — that creates a
duplicate case (and one patient may hold only one active Wellness case).
"""
import json
import pathlib
import sys

SKILLS = pathlib.Path(__file__).resolve().parents[2]          # .claude/skills
CREATE = SKILLS / "test-create-new-case"
PENDING = SKILLS / "test-submit-case-to-pending"

URLS = {
    "dev": "https://dev-dashboard.dnainsights.ai/#/",
    "prod": "https://dashboard.dnainsights.ai/#/",
}


def phase_src(path: pathlib.Path, config_js: str) -> str:
    """Inline a phase script as a JS expression, substituting its __CONFIG__."""
    src = path.read_text()
    if "__CONFIG__" not in src:
        if config_js not in (None, "null"):
            raise SystemExit(f"{path.name} has no __CONFIG__ placeholder")
        return src
    return src.replace("__CONFIG__", config_js)


def main() -> None:
    argv = sys.argv[1:]
    only, seed_case = None, None
    if "--only" in argv:
        i = argv.index("--only")
        only = {p.strip() for p in argv[i + 1].split(",")}
        del argv[i : i + 2]
    if "--case-id" in argv:
        i = argv.index("--case-id")
        seed_case = argv[i + 1]
        del argv[i : i + 2]

    medicare_id = argv[0] if argv else sys.exit("need medicare_id")
    env = argv[1] if len(argv) > 1 else "dev"
    out_path = pathlib.Path(argv[2]) if len(argv) > 2 else pathlib.Path("composite-to-pending.js")
    url = URLS[env]

    case_data = json.loads((CREATE / "data/case-data.json").read_text())
    pss_data = json.loads((PENDING / "data/pss-data.json").read_text())

    cfg01 = {
        "url": url,
        "email": case_data["sale_account"]["email"],
        "password": case_data["sale_account"]["password"],
        "medicareId": medicare_id,
        "patient": case_data["patient"],
        "additional": case_data["additional_information"],
    }
    cfg02 = {k: case_data[k] for k in ("opt_in_consent", "primary_care_provider", "family_history")}
    pss01_base = {
        "url": url,
        "email": pss_data["pss_account"]["email"],
        "password": pss_data["pss_account"]["password"],
    }
    cfg_pss02 = {"compliance": pss_data["compliance"], "medications": pss_data["medications"]}

    parts = {
        "fast01": phase_src(CREATE / "scripts/fast-01-login-create-fill.js", json.dumps(cfg01)),
        "fast02": phase_src(CREATE / "scripts/fast-02-save-sections.js", json.dumps(cfg02)),
        "fast03": phase_src(CREATE / "scripts/fast-03-submit-verify.js", "null"),
        "fast04": phase_src(CREATE / "scripts/fast-04-logout.js", "null"),
        # caseId is only known after phase 1 → close over the composite's variable
        "pss01": phase_src(PENDING / "scripts/pss-01-login-open-case.js",
                           f"Object.assign({{}}, {json.dumps(pss01_base)}, {{ caseId }})"),
        "pss02": phase_src(PENDING / "scripts/pss-02-fill-sections.js", json.dumps(cfg_pss02)),
        "pss03": phase_src(PENDING / "scripts/pss-03-mark-pending.js", "null"),
    }

    phase_src_map = {
        "1-create-fill": parts["fast01"],
        "2-save-sections": parts["fast02"],
        "3-submit": parts["fast03"],
        "4-logout": parts["fast04"],
        "5-pss-open": parts["pss01"],
        "6-pss-sections": parts["pss02"],
        "7-verify-pending": parts["pss03"],
    }
    if only:
        phase_src_map = {k: v for k, v in phase_src_map.items() if k.split("-")[0] in only}
        if not phase_src_map:
            raise SystemExit(f"--only {sorted(only)} matched no phase")
    phases_js = ",\n    ".join(f"'{name}': {src}" for name, src in phase_src_map.items())
    seed_js = f"'{seed_case}'" if seed_case else "null"

    js = f"""// GENERATED by build-composite-to-pending.py — do not edit by hand.
// Runs create-case → sections → submit → logout → PSS login → sections → Pending
// in ONE browser_run_code_unsafe call, reporting per-phase timings in ms.
async (page) => {{
  const T0 = Date.now();
  const timings = {{}};
  const results = {{}};
  let caseId = {seed_js};                  // seeded on resume; else set after phase 1

  const phases = {{
    {phases_js},
  }};

  for (const [name, fn] of Object.entries(phases)) {{
    const t = Date.now();
    let r;
    try {{
      r = await fn(page);
    }} catch (e) {{
      timings[name] = Date.now() - t;
      return {{ ok: false, failedAt: name, error: String(e).slice(0, 300),
               caseId, timings, totalMs: Date.now() - T0, results }};
    }}
    timings[name] = Date.now() - t;
    results[name] = r;
    if (name === '1-create-fill') caseId = r && r.caseId;
    if (!r || r.ok !== true) {{
      return {{ ok: false, failedAt: name, caseId, timings, totalMs: Date.now() - T0, results }};
    }}
  }}

  return {{
    ok: true,
    caseId,
    patientId: (results['1-create-fill'] || {{}}).patientId,
    status: (results['7-verify-pending'] || {{}}).status,
    timings,
    totalMs: Date.now() - T0,
    results,
  }};
}}
"""
    out_path.write_text(js)
    scope = ",".join(sorted(phase_src_map)) if only else "all 7 phases"
    print(f"wrote {out_path} ({len(js.splitlines())} lines) env={env} "
          f"medicare_id={medicare_id} phases={scope} seeded_case={seed_case or '-'}")


if __name__ == "__main__":
    main()
